name: auto_text_resizer_example
description: Example app to demonstrate the auto_text_resizer package.
publish_to: "none" # prevent publishing the example app

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ✅ use the local package from parent directory
  auto_text_resizer:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
