name: auto_text_resizer
description: >
  A lightweight Flutter widget that automatically resizes text to fit its container.
  Useful for dynamic layouts, buttons, and titles.
version: 0.0.1
homepage: https://github.com/yourusername/auto_text_resizer
repository: https://github.com/yourusername/auto_text_resizer
issue_tracker: https://github.com/yourusername/auto_text_resizer/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

topics:
  - text
  - typography
  - auto-resize
